example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = "katalog"

urlpatterns = [
    path("", show_catalog, name="show_katalog"),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_xml, show_json

app_name = "mywatchlist"

urlpatterns = [
    path("", show_watchlist, name="show_watchlist"),
    path("html/", show_watchlist, name="show_watchlist"),
    path("xml/", show_xml, name="show_xml"),
    path("json/", show_json, name="show_json"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path("katalog/", include("katalog.urls")),
    path("mywatchlist/", include("mywatchlist.urls")),
    path("todolist/", include("todolist.urls")),
]

# TODO: Implement Routings Here

todolist/urls.py
from todolist.views import *
from django.urls import path

app_name = "todolist"

urlpatterns = [
    path("", show_todolist, name="show_todolist"), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path("new-task/", new_task, name="new_task"),
    path("is_finished_status/<int:id_task>", is_finished_status, name="is_finished_status"),
    path("remove/<int:id_task>", remove, name="remove"),
    path("json/", show_todolist_json, name="show_todolist_json"),
    path("add_ajax/", add_ajax, name="add_ajax"),
    path("delete_ajax/<int:id>", delete_ajax, name="delete_ajax"),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models
 
class MyWatchList(models.Model):
    watched = models.CharField(max_length=5)
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from multiprocessing import context
from django.shortcuts import render
from katalog.models import CatalogItem 

# TODO: Create your views here.
def show_catalog(request):
    data_barang = CatalogItem.objects.all()
    context = {
        "list_barang": data_barang,
        "nama": "Ahmad Hanif",
        "npm": "2106750603"
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

def show_watchlist(request):
    data = MyWatchList.objects.all()
    context = {
        "watchlist":  data,
        "nama": "Ahmad Hanif Adisetya",
        "npm": "2106750603"
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from datetime import date
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core import serializers

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data = Task.objects.filter(user=request.user)
    context = {
        "list_task" : data,
        "name" : "Ahmad Hanif Adisetya",
        "npm" : "2106750603",
        "last_login" : request.COOKIES["last_login"]
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_todolist_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def add_ajax(request):
    if request.method == "POST":
        title = request.POST.get("title")
        deskripsi = request.POST.get("description")
        task = Task.objects.create(title=title,description=deskripsi,user=request.user)
        data = {
            "fields":{
                "title":task.title,
                "date":task.date,
                "description":task.description,
                "status":task.is_finished,
            },
            "pk":task.pk
        }
        return JsonResponse(data)

def delete_ajax(request, id):
    if request.method == "DELETE":
        task = Task.objects.get(pk=id)
        task.delete()
        data = {
            "fields":{
                "title":task.title,
                "date":task.date,
                "description":task.description,
                "status":task.is_finished,
            },
            "pk":task.pk
        }
        return JsonResponse(data)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account is successfully made!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
            response.set_cookie('last_login', str(datetime.datetime.now())) 
            return response
        else:
            messages.info(request, 'Username or Password is incorrect!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

class TaskForm(forms.Form):
    title = forms.CharField(label="Title")
    description = forms.CharField(label="Description", widget=forms.Textarea())

@login_required(login_url='/todolist/login/')
def new_task(request):
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task_data = Task(
                user = request.user,
                title = form.cleaned_data["title"],
                description = form.cleaned_data["description"],
            )
            task_data.save()
            return redirect('todolist:show_todolist')

    context = {"form":form}
    return render(request, "new_task.html", context)

@login_required(login_url='/todolist/login/')
def is_finished_status(request, id_task):
    task = Task.objects.get(pk=id_task)
    task.is_finished = not(task.is_finished)
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def remove(request, id_task):
    Task.objects.get(pk=id_task).delete()
    return redirect('todolist:show_todolist')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 2 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
<style>
    body {
        font-family: 'Courier New', Courier, monospace;
        background-color: beige;
    }
    h1 {
        text-align:center;
    }

    .credentials {
        text-align:center;
    }

    table, th, td {
        border: 1px solid;
        border-color:#f00;
        border-collapse:collapses;
        background-color:rgb(247, 247, 242);
    }

    table {
        margin-left:auto;
        margin-right:auto;
    }

    th, td {
        padding:10px;
    }

    .btn {
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:20px;
        width:100px;
        padding:10px;
        text-align:center;
        border:5px;
        border-radius:5px;
        cursor:pointer;
        color:#fff;
        background-color:#f00;
        margin:auto;
        margin-top:10px
    }
    
</style>

<script>
    function popup() {
        alert("Selamat, kamu sudah banyak menonton!")
    }
</script>

{% extends 'base.html' %}
  {% block content %}
    <h1>Assignment 3 PBP/PBD</h1>

    <class class="credentials">
        <h5>Name: </h5>
        <p>{{nama}}</p>
    
        <h5>Student ID: </h5>
        <p>{{npm}}</p>
    </class>

    <input type="button" class="btn" value="Click Me!" onclick="popup()">

    <br>
    <table width="80%">
        <tr>
            <th>Watched</th>
            <th>Title of Movie/Series</th>
            <th>Rating</th>
            <th>Release Date</th>
            <th>Review</th>
        </tr>
        {% for movie in watchlist %}
            <tr>
                <th>{{movie.watched}}</th>
                <th>{{movie.title}}</th>
                <th>{{movie.rating}}</th>
                <th>{{movie.release_date}}</th>
                <th>{{movie.review}}</th>
            </tr>
        {% endfor %}
    </table>
  {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

todolist/templates/backup.html
<style>
    body {
        font-family: 'Courier New', Courier, monospace;
        background-image: linear-gradient(to bottom left, beige, beige);
    }

    h1 {
        text-align:center;
    }

    .credentials {
        text-align:center;
    }

    .card {
        background-color: beige;
    }

    .btn {
        margin:auto;
        display:block;
    }
</style>

<body>
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Todolist</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock meta %}

  {% block content %}

    <h1>Assignment 4 PBP</h1>
    <class class="credentials">
        <h5>{{name}} {{npm}}</h5>
        <p>{{user.get_username}}'s To Do List</p>
        <a href="{% url 'todolist:new_task' %}" class="btn btn-info">New Task</a>
    </class>
    
    <br><br>
    {% if not list_task %}
    <div class="d-flex justify-content-center">
        <h3>No Task On Your To Do List</h3>
    </div>
    <br>
    {% else %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for task in list_task %}
        <div class="col" id="card">
          <div class="card h-100 border-danger">
            <div class="card-body d-flex flex-column">
              <h4 class="card-title">{{task.title}} | {% if task.is_finished is True %}
                ✓
                {% else %}
                ✕
                {% endif %}
              </h4>
              <h6 class="card-subtitle mb-2 text-muted">{{task.date}}</h6>
              <p class="card-text">{{task.description}}</p>
              <div class="flex justify-between gap-3">
               <div class="flex flex-col justify-center rounded">
                  <a href="{% url 'todolist:is_finished_status' task.id %}" class="btn btn-success">Change Status</a> 
                  <a href="{% url 'todolist:remove' task.id %}" class="btn btn-warning">Remove Task</a> 
               </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <p>Sesi terakhir login: {{ last_login }}</p>
    <a href="{% url 'todolist:logout' %}" class="btn btn-info">Logout</a>

{% endblock content %}
</body>

todolist/templates/login.html
<style>
    body {
        font-family: 'Courier New', Courier, monospace;
        display: flex;
        align-items: center;
        justify-content: center;
        background-image: linear-gradient(to bottom left, beige, beige);
    }

    .login form input[type="submit"]{
        background-color: rgb(0, 132, 0);
        color: beige;
        margin-top: 5px;
    }

    h1 {
        text-align:center;
    }

    .credentials {
        text-align:center;
    }

    table, th, td {
        border: 1px solid;
        border-color:#f00;
        border-collapse:collapses;
        background-color:rgb(247, 247, 242);
    }

    table {
        margin-left:auto;
        margin-right:auto;
    }

    th, td {
        padding:10px;
    }    

    .signup {
        text-align:center;
    }

    li {
        text-align:center;
    }
</style>
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <class class="signup">
        <p>Don't have an account? <a href="{% url 'todolist:register' %}">Sign up</a></p>
    </class>
</div>

{% endblock content %}

todolist/templates/new_task.html
<style>
    body {
        font-family: 'Courier New', Courier, monospace;
        display: flex;
        align-items: center;
        justify-content: center;
        background-image: linear-gradient(to bottom left, beige, beige);
    }

    .login form input[type="submit"]{
        background-color: rgb(0, 132, 0);
        color: beige;
        margin-top: 5px;
    }

    h1 {
        text-align:center;
    }

    .credentials {
        text-align:center;
    }

    table, th, td {
        border: 1px solid;
        border-color:#f00;
        border-collapse:collapses;
        background-color:rgb(247, 247, 242);
    }

    table {
        margin-left:auto;
        margin-right:auto;
    }

    th, td {
        padding:10px;
    }    
</style>

{% extends 'base.html' %}

{% block meta %}
<title>Add New Task</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Add New Task</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Add Task"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/register.html
<style>
    body {
        font-family: 'Courier New', Courier, monospace;
        display: flex;
        align-items: center;
        justify-content: center;
        background-image: linear-gradient(to bottom left, beige, beige);
    }

    .login form input[type="submit"]{
        background-color: rgb(0, 132, 0);
        color: beige;
        margin-top: 5px;
    }

    h1 {
        text-align:center;
    }

    .credentials {
        text-align:center;
    }

    table, th, td {
        border: 1px solid;
        border-color:#f00;
        border-collapse:collapses;
        background-color:rgb(247, 247, 242);
    }

    table {
        margin-left:auto;
        margin-right:auto;
    }

    th, td {
        padding:10px;
    }    
</style>

{% extends 'base.html' %}

{% block meta %}
<title>Account Register</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register Form</h1>  

        <form method="POST">  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Done"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
<style>
    body {
        font-family: 'Courier New', Courier, monospace;
        background-image: linear-gradient(to bottom left, beige, beige);
    }

    h1 {
        text-align:center;
    }

    .credentials {
        text-align:center;
    }

    .btn {
        margin:auto;
        display:block;
    }

  .modal {
  display: none; 
  position: fixed; 
  z-index: 1; 
  left: 0;
  top: 0;
  width: 50px; 
  height: 50px; 
  overflow: auto; 
  background-color: rgba(0,0,0,0.4);
}

.modal-content {
  background-image: linear-gradient(to bottom left, beige, beige);
  margin: 15% auto; 
  padding: 20px;
  border: 1px solid #888;
  width: 50px; 
}
</style>

<body>
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Todolist</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock meta %}
{% block content %}

<div id="myModal" class="modal">
  <dialog class="modal-content">
    <p>Add new task</p>
    <label for="recipient-name" class="col-form-label">Title:</label>
    <input type="text" class="form-control" id="title">
    <label for="message-text" class="col-form-label">Description:</label>
    <textarea class="form-control" id="description"></textarea>
    <button type="button" class="btn btn-success" id="done">Submit</button>
  </dialog>
</div>

  <h1>Assignment 4 PBP</h1>
  <class class="credentials">
      <h5>{{name}} {{npm}}</h5>
      <p>{{user.get_username}}'s To Do List</p>
      <button type="button" class="btn btn-info" id="myBtn">New Task</button> 
  </class>

    <br><br>
    {% if not list_task %}
    <div class="d-flex justify-content-center">
        <h3>No Task On Your To Do List</h3>
    </div>
    <br>
    {% else %}
    <div class="container">
      <div class="row row-cols-1 row-cols-md-3 g-4" id="myCards">
      </div>
    </div> 
    {% endif %}

    <p>Sesi terakhir login: {{ last_login }}</p>
    <a href="{% url 'todolist:logout' %}" class="btn btn-info">Logout</a>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="js/jquery/jquery-3.1.0.js"></script>
  <script src="plugins/bootstrap/js/bootstrap.min.js"></script>
  <script>
  var modal = document.getElementById("myModal");
  var btn = document.getElementById("myBtn");
  var sbmt = document.getElementById("done");

  btn.onclick = function() {
    modal.style.display = "block";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }

  sbmt.onclick = function() {
    modal.style.display = "none";
    const title = $("#title").val()
    const desc = $("#description").val()
    const data = {title:title, description:desc, csrfmiddlewaretoken:"{{ csrf_token }}"}
    $.ajax({url:"/todolist/add_ajax/", data:data, method:"POST"}).done(function(resp){
      $("#myCards").append(`
        <div class="col" id="card${resp.pk}">
          <div class="card h-100 border-danger">
            <div class="card-body d-flex flex-column">
              <h4 class="card-title">${resp.fields.title} ${resp.fields.is_finished ? "✓" : "✕"}</h4>
              <h6 class="card-subtitle mb-2 text-muted">${resp.fields.date}</h6>
              <p class="card-text">${resp.fields.description}</p>
              <div class="flex justify-between gap-3">
              <div class="flex flex-col justify-center rounded">
                    <button class="btn btn-success" ><a href="/todolist/is_finished_status/${resp.pk}">Change Status</a></button> 
                  <button class="btn btn-warning"><a onclick=deleteDone(${resp.pk})>Remove Task</a></button> 
              </div>
              </div>
            </div>
          </div>
        </div>
      `)
    })
    document.getElementById("title").value = ""
    document.getElementById("description").value = ""
  }

  $(document).ready(function(){
    $.get("/todolist/json", function(task){
      for (index=0; index<task.length; index++){
        $("#myCards").append(`
        <div class="col" id="card${task[index].pk}">
          <div class="card h-100 border-danger">
            <div class="card-body d-flex flex-column">
              <h4 class="card-title">${task[index].fields.title} ${task[index].fields.is_finished ? "✓" : "✕"}</h4>
              <h6 class="card-subtitle mb-2 text-muted">${task[index].fields.date}</h6>
              <p class="card-text">${task[index].fields.description}</p>
              <div class="flex justify-between gap-3">
               <div class="flex flex-col justify-center rounded">
                  <button class="btn btn-success" ><a href="/todolist/is_finished_status/${task[index].pk}">Change Status</a></button> 
                  <button class="btn btn-warning"><a onclick=deleteDone(${task[index].pk})>Remove Task</a></button> 
               </div>
              </div>
            </div>
          </div>
        </div>
        `)
      }
    });
  });

  </script>
{% endblock content %}
</body>

<!--
  Percobaan delete
  var deleteDone = function(pk) {
    $.ajax({
      type: "DELETE",
      headers: { "X-CSRFToken": document.getElementsByName("csrfmiddlewaretoken")[0].value },
      url: "{% url 'todolist:delete_ajax' " + pk +" %}",
      encode: true,
    }).done(function(data){
      document.getElementById(`card${pk}`).remove();
    }) 
  }
  
-->